const $=s=>document.querySelector(s),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,5);
let S=Object.assign({notes:[],theme:'gun',key:'',model:'gemini-2.5-flash'},JSON.parse(localStorage.nd||'{}'));
const save=()=>{try{localStorage.nd=JSON.stringify(S)}catch(e){alert('Depolama doldu. Yedek alıp eski fotoğrafları silin.')}};
const SEC={classic:['📓','Klasik Defter','Zengin biçimli serbest yazı'],list:['✅','Listeler','Madde madde, işaretlenebilir'],cards:['🗂️','Kutucuklar','Renkli kısa notlar'],map:['🕸️','Bağlantı Haritası','Kutuları sürükle, birbirine bağla'],journal:['📅','Günlük','Tarihe göre kayıt']};
const FONTS=['Nunito','Lora','Merriweather','Playfair Display','Caveat','Pacifico','Roboto Mono','Georgia','Arial'];
const COLS=['#ffffff','#fde68a','#bbf7d0','#bfdbfe','#fbcfe8','#ddd6fe','#fed7aa','#e5e7eb'];
const TH={gun:'Gün',gece:'Gece',orman:'Orman',gul:'Gül',kum:'Kum',okyanus:'Okyanus'};
let V={p:'home'},rng,tm;
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const txt=h=>{const d=document.createElement('div');d.innerHTML=h;return d.textContent};
const get=id=>S.notes.find(n=>n.id==id),tags=()=>[...new Set(S.notes.flatMap(n=>n.tags))].sort();
const go=(p,o={})=>{V=Object.assign({p},o);render();scrollTo(0,0)};
const card=n=>`<div class="card" style="background:${n.color}" data-act="open" data-id="${n.id}"><b>${esc(n.title)||'Başlıksız'}</b><p style="font-family:${n.font}">${esc((n.sec=='list'?n.items.map(i=>i.t).join(', '):n.text).slice(0,140))}</p>${n.imgs[0]?`<img src="${n.imgs[0]}">`:''}<div class="tg">${n.tags.map(t=>`<i>#${esc(t)}</i>`).join('')}</div></div>`;
const chips=(cur,act)=>`<div class="chips"><button class="${cur?'':'on'}" data-act="${act}" data-t="">Tümü</button>${tags().map(t=>`<button class="${cur==t?'on':''}" data-act="${act}" data-t="${esc(t)}">#${esc(t)}</button>`).join('')}</div>`;
function home(){const r=[...S.notes].sort((a,b)=>b.u-a.u).slice(0,6);return `<h1>Defterim</h1><p class="mu">Bir bölüm seç ya da yeni not başlat.</p><div class="grid">${Object.entries(SEC).map(([k,v])=>`<button class="sec" data-act="sec" data-s="${k}">${v[0]}<b>${v[1]}</b><small>${v[2]}</small><small>${S.notes.filter(n=>n.sec==k).length} not</small></button>`).join('')}</div><h3>Son düzenlenenler</h3>${r.length?`<div class="cols">${r.map(card).join('')}</div>`:'<div class="empty">Henüz not yok.</div>'}`}
function sec(){const k=V.s,l=S.notes.filter(n=>n.sec==k&&(!V.tag||n.tags.includes(V.tag)));return `<header><button data-act="home">←</button><h2>${SEC[k][0]} ${SEC[k][1]}</h2><button class="pri" data-act="new">+ Yeni</button></header>${chips(V.tag,'ftag')}${k=='map'?`<p class="mu">Kutuya dokun, sonra başka kutuya dokun: bağlanır (tekrar dokunursan kopar). ✎ ile içeriği aç.</p><div id="mw"><div id="map"><svg id="ln"></svg>${l.map(n=>`<div class="bx${V.sel==n.id?' sel':''}" data-id="${n.id}" style="left:${n.x}px;top:${n.y}px;background:${n.color}">${esc(n.title)||'Başlıksız'}<button data-act="open" data-id="${n.id}">✎</button></div>`).join('')}</div></div>`:l.length?`<div class="${k=='cards'?'cols':''}">${l.sort((a,b)=>b.u-a.u).map(card).join('')}</div>`:'<div class="empty">Bu bölümde not yok. “+ Yeni” ile başla.</div>'}`}
function ed(){const n=get(V.id),L=n.sec=='list';return `<header><button data-act="back">←</button><h2>${SEC[n.sec][1]}</h2><button data-act="del">🗑️</button></header>
<input id="ti" class="ti" placeholder="Başlık" value="${esc(n.title)}"><input id="tg" placeholder="Etiketler (virgülle ayır)" value="${esc(n.tags.join(', '))}">
${L?'':`<div class="bar" id="bar"><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><button data-cmd="strikeThrough"><s>S</s></button><button data-cmd="formatBlock" data-v="h2">H</button><button data-cmd="insertUnorderedList">•</button><button data-cmd="insertOrderedList">1.</button><button data-cmd="justifyLeft">⇤</button><button data-cmd="justifyCenter">↔</button><button data-cmd="justifyRight">⇥</button><select id="fn"><option value="">Yazı tipi</option>${FONTS.map(f=>`<option style="font-family:${f}">${f}</option>`).join('')}</select><select id="fz"><option value="">Boyut</option>${[1,2,3,4,5,6,7].map(i=>`<option>${i}</option>`).join('')}</select><input type="color" id="fc" title="Yazı rengi" value="#000000"><input type="color" id="hc" title="Vurgu rengi" value="#ffff00"><button data-cmd="removeFormat">⌫</button></div>`}
${L?`<div id="its">${n.items.map((i,x)=>`<div class="it"><input type="checkbox" ${i.d?'checked':''} data-act="chk" data-i="${x}"><input class="${i.d?'done':''}" data-it="${x}" value="${esc(i.t)}"><button data-act="rmit" data-i="${x}">×</button></div>`).join('')}</div><input id="ni" placeholder="Yeni madde yaz, Enter'a bas">`:`<div id="bd" contenteditable style="font-family:${n.font}">${n.html}</div>`}
<div class="im">${n.imgs.map((s,i)=>`<span><img src="${s}"><button data-act="rmimg" data-i="${i}">×</button></span>`).join('')}</div>
<label class="btn">📷 Fotoğraf ekle<input type="file" accept="image/*" multiple hidden id="ph"></label>
<p class="mu">Not rengi</p><div class="th">${COLS.map(c=>`<button class="sw ${n.color==c?'on':''}" style="background:${c}" data-act="col" data-c="${c}"></button>`).join('')}</div><p class="mu">${new Date(n.c).toLocaleString('tr')}</p>`}
function res(){const q=(V.q||'').toLowerCase(),m=V.m||'all',r=S.notes.filter(n=>(!V.s||n.sec==V.s)&&(!V.tag||n.tags.includes(V.tag))&&(!q||(m=='title'?n.title:m=='tag'?n.tags.join(' '):m=='text'?n.text+n.items.map(i=>i.t).join(' '):n.title+' '+n.tags.join(' ')+' '+n.text+' '+n.items.map(i=>i.t).join(' ')).toLowerCase().includes(q)));return `<p class="mu">${r.length} sonuç</p><div class="cols">${r.map(card).join('')}</div>`}
function search(){return `<h1>Ara</h1><input id="q" placeholder="Başlık, etiket veya içerik…" value="${esc(V.q)}"><div class="grid"><select id="m">${[['all','Hepsinde'],['title','Başlıkta'],['tag','Etikette'],['text','İçerikte']].map(([k,t])=>`<option value="${k}" ${V.m==k?'selected':''}>${t}</option>`).join('')}</select><select id="sf"><option value="">Tüm bölümler</option>${Object.entries(SEC).map(([k,v])=>`<option value="${k}" ${V.s==k?'selected':''}>${v[1]}</option>`).join('')}</select></div><br>${chips(V.tag,'stag')}<button data-act="askq">✨ Bunu yapay zekâya sor</button><div id="res">${res()}</div>`}
function ai(){return `<h1>✨ Yapay Zekâ</h1><p class="mu">Sorularını notlarından yola çıkarak yanıtlar ve aradığını bulmana yardım eder.</p><textarea id="aq" rows="3" placeholder="Örn: Geçen ay hangi kitapları not almıştım?">${esc(V.aq)}</textarea><button class="pri" data-act="ask">Sor</button><div id="an">${V.an?`<div class="ans">${V.an}</div>`:''}</div>`}
function set(){return `<h1>Ayarlar</h1><h3>Tema</h3><div class="th">${Object.entries(TH).map(([k,v])=>`<button class="${S.theme==k?'pri':''}" data-act="theme" data-k="${k}">${v}</button>`).join('')}</div><h3>Yedekleme</h3><div class="th"><button class="pri" data-act="bak">💾 Yedek al (klasör seç)</button><label class="btn">♻️ Yedekten yükle<input type="file" accept=".json" hidden id="rs"></label></div><h3>Gemini</h3><input id="gk" type="password" placeholder="Gemini API anahtarı" value="${esc(S.key)}"><input id="gm" placeholder="Model" value="${esc(S.model)}"><p class="mu">Anahtar yalnızca bu cihazda saklanır. aistudio.google.com adresinden ücretsiz alınır.</p>`}
function render(){document.body.dataset.t=S.theme;$('#v').innerHTML=({home,sec,ed,search,ai,set}[V.p])();if(V.p=='sec'&&V.s=='map')drawMap();if(V.p=='ed'&&get(V.id).sec=='list')0}
function drawMap(){$('#ln').innerHTML=S.notes.filter(n=>n.sec=='map').flatMap(n=>(n.links||[]).map(t=>{const m=get(t);return m&&n.id<m.id?`<line x1="${n.x+60}" y1="${n.y+30}" x2="${m.x+60}" y2="${m.y+30}"/>`:''})).join('')}
function newNote(s){const n={id:uid(),sec:s,title:'',tags:[],html:'',text:'',items:[],imgs:[],color:'#ffffff',font:'Nunito',c:Date.now(),u:Date.now(),x:30+Math.random()*300|0,y:30+Math.random()*300|0,links:[]};if(s=='journal')n.title=new Date().toLocaleDateString('tr',{weekday:'long',day:'numeric',month:'long',year:'numeric'});S.notes.push(n);save();go('ed',{id:n.id,back:V})}
const touch=n=>{n.u=Date.now();clearTimeout(tm);tm=setTimeout(save,300)};
const img=f=>new Promise(r=>{const i=new Image;i.onload=()=>{const k=Math.min(1,900/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);r(c.toDataURL('image/jpeg',.7))};i.src=URL.createObjectURL(f)});
const ex=(c,v)=>{const b=$('#bd');b.focus();if(rng){const s=getSelection();s.removeAllRanges();s.addRange(rng)}document.execCommand(c,false,v);const n=get(V.id);n.html=b.innerHTML;n.text=b.innerText;touch(n)};
document.addEventListener('selectionchange',()=>{const s=getSelection();if(s.rangeCount&&$('#bd')?.contains(s.anchorNode))rng=s.getRangeAt(0).cloneRange()});
document.addEventListener('pointerdown',e=>{if(e.target.closest('#bar')&&!['SELECT','INPUT'].includes(e.target.tagName))e.preventDefault()});
document.addEventListener('click',async e=>{const t=e.target.closest('[data-act],[data-cmd],[data-go]');if(!t)return;const d=t.dataset,n=V.id&&get(V.id);
if(d.go)return go(d.go);if(d.cmd)return ex(d.cmd,d.v);
({home:()=>go('home'),sec:()=>go('sec',{s:d.s}),open:()=>go('ed',{id:d.id,back:V}),back:()=>go(V.back?.p||'home',V.back),new:()=>newNote(V.s),ftag:()=>{V.tag=d.t;render()},stag:()=>{V.tag=d.t;render()},
del:()=>{if(confirm('Bu not silinsin mi?')){S.notes=S.notes.filter(x=>x.id!=n.id);S.notes.forEach(x=>x.links=(x.links||[]).filter(l=>l!=n.id));save();go(V.back?.p||'home',V.back)}},
col:()=>{n.color=d.c;touch(n);render()},rmimg:()=>{n.imgs.splice(d.i,1);touch(n);render()},rmit:()=>{n.items.splice(d.i,1);touch(n);render()},chk:()=>{n.items[d.i].d=t.checked;touch(n);render()},
theme:()=>{S.theme=d.k;save();render()},askq:()=>go('ai',{aq:V.q}),ask:askAI,bak:backup}[d.act]||(()=>0))()});
document.addEventListener('input',e=>{const t=e.target,n=V.id&&get(V.id);if(V.p=='ed'){if(t.id=='ti'){n.title=t.value;touch(n)}else if(t.id=='tg'){n.tags=t.value.split(',').map(x=>x.trim()).filter(Boolean);touch(n)}else if(t.id=='bd'){n.html=t.innerHTML;n.text=t.innerText;touch(n)}else if(t.dataset.it){n.items[t.dataset.it].t=t.value;touch(n)}}
if(t.id=='q'){V.q=t.value;$('#res').innerHTML=res()}if(t.id=='aq')V.aq=t.value;if(t.id=='gk'){S.key=t.value.trim();save()}if(t.id=='gm'){S.model=t.value.trim();save()}});
document.addEventListener('change',async e=>{const t=e.target,n=V.id&&get(V.id);
if(t.id=='m'||t.id=='sf'){V[t.id=='m'?'m':'s']=t.value;$('#res').innerHTML=res()}
if(t.id=='fn'||t.id=='fz'||t.id=='fc'||t.id=='hc'){const v=t.value;if(t.id=='fn'){if(getSelection().isCollapsed&&(!rng||rng.collapsed)){n.font=v||'Nunito';$('#bd').style.fontFamily=n.font;touch(n)}else ex('fontName',v)}else ex({fz:'fontSize',fc:'foreColor',hc:'hiliteColor'}[t.id],v)}
if(t.id=='ph'){for(const f of t.files)n.imgs.push(await img(f));touch(n);render()}
if(t.id=='rs'){const j=JSON.parse(await t.files[0].text());if(j.notes&&confirm('Mevcut notlar yedekle değiştirilsin mi? (İptal: birleştir)'))S.notes=j.notes;else if(j.notes){j.notes.forEach(x=>{if(!get(x.id))S.notes.push(x)})}save();alert('Yedek yüklendi.');go('home')}});
document.addEventListener('keydown',e=>{if(e.target.id=='ni'&&e.key=='Enter'&&e.target.value.trim()){const n=get(V.id);n.items.push({t:e.target.value.trim(),d:0});touch(n);render();$('#ni').focus()}});
let dr;document.addEventListener('pointerdown',e=>{const b=e.target.closest('.bx');if(!b||e.target.dataset.act)return;const n=get(b.dataset.id);dr={b,n,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y,mv:0};b.setPointerCapture(e.pointerId)});
document.addEventListener('pointermove',e=>{if(!dr)return;const dx=e.clientX-dr.x,dy=e.clientY-dr.y;if(Math.abs(dx)+Math.abs(dy)>6)dr.mv=1;if(dr.mv){dr.n.x=Math.max(0,dr.ox+dx);dr.n.y=Math.max(0,dr.oy+dy);dr.b.style.left=dr.n.x+'px';dr.b.style.top=dr.n.y+'px';drawMap()}});
document.addEventListener('pointerup',()=>{if(!dr)return;const{n,mv}=dr;dr=null;if(mv)return save();if(V.sel&&V.sel!=n.id){const a=get(V.sel);a.links=a.links||[];n.links=n.links||[];const has=a.links.includes(n.id);a.links=a.links.filter(x=>x!=n.id);n.links=n.links.filter(x=>x!=a.id);if(!has){a.links.push(n.id);n.links.push(a.id)}V.sel=null;save()}else V.sel=V.sel==n.id?null:n.id;render()});
async function askAI(){const q=($('#aq').value||'').trim(),o=$('#an');if(!q)return;if(!S.key){o.innerHTML='<div class="ans">Önce Ayarlar bölümüne Gemini API anahtarını gir.</div>';return}
o.innerHTML='<div class="ans">Notların taranıyor…</div>';const w=q.toLowerCase().split(/\s+/).filter(x=>x.length>2),body=n=>n.title+' '+n.tags.join(' ')+' '+n.text+' '+n.items.map(i=>i.t).join(' ');
let r=S.notes.map(n=>({n,s:w.filter(x=>body(n).toLowerCase().includes(x)).length})).sort((a,b)=>b.s-a.s||b.n.u-a.n.u).slice(0,25),ctx='';for(const{n}of r){const p=`### ${n.title||'Başlıksız'} [${SEC[n.sec][1]}] etiketler: ${n.tags.join(', ')} tarih: ${new Date(n.c).toLocaleDateString('tr')}\n${body(n).slice(0,1500)}\n\n`;if((ctx+p).length>24000)break;ctx+=p}
try{const R=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${S.model}:generateContent?key=${S.key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`Sen kullanıcının not defterinin asistanısın. Yalnızca aşağıdaki notlara dayanarak Türkçe, kısa ve net yanıt ver. Yanıtta hangi notlardan yararlandığını başlıklarıyla belirt. Notlarda cevap yoksa bunu söyle ve kullanıcıya hangi başlık/etiketle arayabileceğini öner.\n\nNOTLAR:\n${ctx}\nSORU: ${q}`}]}]})}),j=await R.json();const a=j.candidates?.[0]?.content?.parts?.map(p=>p.text).join('')||j.error?.message||'Yanıt alınamadı.';V.an=esc(a).replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>');o.innerHTML=`<div class="ans">${V.an}</div>`}catch(x){o.innerHTML='<div class="ans">Bağlantı hatası: internet ve anahtarı kontrol et.</div>'}}
async function backup(){const s=JSON.stringify(S.notes.length?{notes:S.notes,date:new Date().toISOString()}:{notes:[]}),name=`defterim-yedek-${new Date().toISOString().slice(0,10)}.json`;
try{if(window.showDirectoryPicker){const d=await showDirectoryPicker({mode:'readwrite'}),f=await d.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(s);await w.close();alert('Yedek seçtiğin klasöre kaydedildi.')}else throw 0}catch(e){if(e&&e.name=='AbortError')return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'application/json'}));a.download=name;a.click()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
render();
